id: P004148
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25174
  title: མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད་བློ་གསལ་བློའི་པདྨ་ཁ་འབྱེད།
  author: ''
  volumes:
    f5644802bfff474780a9e3887d56bc1d:
      image_group_id: I1KG25176
      title: ''
      volume_number: 1
      total_pages: 516
