id: P004148
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:56:25.719270
source_metadata:
  id: bdr:W1KG25174
  title: མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད་བློ་གསལ་བློའི་པདྨ་ཁ་འབྱེད།
  author: ''
  volumes:
    f5644802bfff474780a9e3887d56bc1d:
      image_group_id: I1KG25176
      title: ''
      volume_number: 1
      total_pages: 516
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
